[project]
name = "cobbler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dacite>=1.9.2",
    "numpy>=2.4.0",
    "safetensors>=0.7.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
